# Numpy Part-1

In [1]:
import numpy as np

### 1. Numpy 배열(N-dimensional array)

In [2]:
a = np.array([1,4,5,8], float)
a

array([1., 4., 5., 8.])

In [3]:
a.dtype, a.shape, a.ndim, a.size

(dtype('float64'), (4,), 1, 4)

In [4]:
b = np.arange(6).reshape(2,3)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [5]:
b.shape

(2, 3)

In [6]:
# Vector(1차원)
a = np.array([1,3, 4, 7], dtype=np.float32)
a

array([1., 3., 4., 7.], dtype=float32)

In [8]:
# Metrix(2차원)
b = np.array([[1,2,4],[4,3,9],[3,7,8]])
b

array([[1, 2, 4],
       [4, 3, 9],
       [3, 7, 8]])

In [9]:
b.dtype, b.shape, b.ndim, b.size

(dtype('int32'), (3, 3), 2, 9)

In [11]:
# Tensor(3차원)
c = np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [12]:
c.dtype, c.shape, c.ndim, c.size

(dtype('int32'), (2, 3, 4), 3, 24)

In [13]:
type(c)

numpy.ndarray

- data type(dtype)

In [15]:
np.array([1,2,3,4], dtype = np.int32)
np.array([1,2,3,4], dtype = np.float32)

array([1., 2., 3., 4.], dtype=float32)

- reshape()

In [16]:
c.size

24

In [17]:
c.reshape(4,6)      # size가 같으면 reshape 가능

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [18]:
c.reshape(-1,3,2)       # 값 하나는 -1로 사용할 수 있음

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [19]:
a

array([1., 3., 4., 7.], dtype=float32)

In [20]:
a.reshape(-1,1)             # 4 x 1

array([[1.],
       [3.],
       [4.],
       [7.]], dtype=float32)

In [21]:
a.reshape(1,-1)             # 1 x 4

array([[1., 3., 4., 7.]], dtype=float32)

In [22]:
# shape은 튜플
a.reshape(-1,)

array([1., 3., 4., 7.], dtype=float32)

In [23]:
# 1차원으로 변경
b.flatten()

array([1, 2, 4, 4, 3, 9, 3, 7, 8])

### 2. Indexing and Slicing

In [24]:
a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
a[2][3], a[2,3], a[-1,-1]

(12, 12, 12)

In [29]:
# 2,3,6,7 slicing
a[0:2, 1:3]

array([[2, 3],
       [6, 7]])