# Numpy Part-1

In [1]:
import numpy as np

### 1. Numpy 배열(N-dimensional array)

In [2]:
a = np.array([1,4,5,8], float)
a

array([1., 4., 5., 8.])

In [3]:
a.dtype, a.shape, a.ndim, a.size

(dtype('float64'), (4,), 1, 4)

In [4]:
b = np.arange(6).reshape(2,3)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [5]:
b.shape

(2, 3)

In [6]:
# Vector(1차원)
a = np.array([1,3, 4, 7], dtype=np.float32)
a

array([1., 3., 4., 7.], dtype=float32)

In [8]:
# Metrix(2차원)
b = np.array([[1,2,4],[4,3,9],[3,7,8]])
b

array([[1, 2, 4],
       [4, 3, 9],
       [3, 7, 8]])

In [9]:
b.dtype, b.shape, b.ndim, b.size

(dtype('int32'), (3, 3), 2, 9)

In [11]:
# Tensor(3차원)
c = np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [12]:
c.dtype, c.shape, c.ndim, c.size

(dtype('int32'), (2, 3, 4), 3, 24)

In [13]:
type(c)

numpy.ndarray

- data type(dtype)

In [15]:
np.array([1,2,3,4], dtype = np.int32)
np.array([1,2,3,4], dtype = np.float32)

array([1., 2., 3., 4.], dtype=float32)

- reshape()