In [2]:
import numpy as np

1. 넘파이를 사용하여 다음과 같은 행렬을 만드시오.
<pre>
10 20 30 40
50 60 70 80

In [3]:
np.array([[10,20,30,40],[50,60,70,80]])
# np.arange(10,81,10).reshape(2,4)

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

2.

In [4]:
m = np.array([[ 0, 1, 2, 3, 4], 
                [ 5, 6, 7, 8, 9], 
                [10, 11, 12, 13, 14]])

In [5]:
# 이 행렬에서 값 7 을 인덱싱한다.
m[1,2]

7

In [6]:
# 이 행렬에서 값 14 을 인덱싱한다.
m[-1,-1]

14

In [7]:
# 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
m[1:2, 1:3]

array([[6, 7]])

In [8]:
# 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
m[1:, 2:3]

array([[ 7],
       [12]])

In [9]:
# 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.
m[:-1, 3:]

array([[3, 4],
       [8, 9]])

3. 2번의 행렬 m을 1차원 벡터 f 로 변환한 후 다음의 문제를 푸시오.

In [10]:
f = m.flatten()
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
# 이 배열에서 3의 배수를 찾아라.
f[f%3 == 0]

array([ 0,  3,  6,  9, 12])

In [12]:
# 이 배열에서 4로 나누면 1이 남는 수를 찾아라.
f[f%4 == 1]

array([ 1,  5,  9, 13])

In [13]:
# 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.
# f[np.logical_and(f%3==0,f%4==1)]
f_index = np.logical_and(f%3==0,f%4==1)
f[f_index]

array([9])

4.

In [15]:
# np.eye(5,5,-1,int)*3 +  np.eye(5,5,0,int)*2 + np.eye(5,5,1,int)
np.eye(5,5,k=-1, dtype=int)+np.eye(5,5,k=-1, dtype=int)+np.eye(5,5,k=-1, dtype=int)+np.eye(5,5,k=0, dtype=int)+np.eye(5,5,k=0, dtype=int)+np.eye(5,5,k=1, dtype=int)

array([[2, 1, 0, 0, 0],
       [3, 2, 1, 0, 0],
       [0, 3, 2, 1, 0],
       [0, 0, 3, 2, 1],
       [0, 0, 0, 3, 2]])

5. 0에서 10까지 랜덤 실수값으로 이루어진 5 x 6 형태의 데이터 행렬을 만들고 이 데이터에
대해 다음과 같은 값을 구하시오.

In [16]:
a = np.random.uniform(0,10,30).reshape(5,6).round(4)
a

array([[0.6696, 5.9912, 4.88  , 4.7407, 0.6245, 7.6579],
       [2.5491, 4.6515, 8.2082, 5.8091, 4.4894, 4.2009],
       [2.4167, 1.1   , 3.6199, 5.4347, 1.9219, 2.5992],
       [2.4473, 9.9215, 7.8748, 0.9618, 7.8523, 9.9427],
       [1.6524, 0.3414, 0.8516, 7.8526, 3.2237, 9.6921]])

In [17]:
# 전체의 최댓값
a.max()

9.9427

In [18]:
# 각 행의 합
a.sum(axis = 1)

array([24.5639, 29.9082, 17.0924, 39.0004, 23.6138])

In [19]:
# 각 행의 최댓값
a.max(axis = 1)

array([7.6579, 8.2082, 5.4347, 9.9427, 9.6921])

In [20]:
# 각 열의 평균
a.mean(axis=0)

array([1.94702, 4.40112, 5.0869 , 4.95978, 3.62236, 6.81856])

In [21]:
# 각 열의 최솟값
a.min(axis=0)

array([0.6696, 0.3414, 0.8516, 0.9618, 0.6245, 2.5992])

6. 다음 배열은 첫번째 행(row)에 학번, 두번째 행에 영어 성적, 세번째 행에 수학 성적을 적은
배열이다. 영어 성적을 기준으로 각 열(column)을 재정렬하시오.

In [22]:
a = np.array([[ 1, 2, 3, 4],
        [ 46, 99, 100, 71],
        [ 81, 59, 90, 100]])

In [27]:
eng_index = np.argsort(a[1])
a[:, eng_index[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

7. 주사위를 100번 던지는 가상 실험을 파이썬으로 작성하고, 
던져서 나오는 숫자의 평균을 구하시오.

In [28]:
a = np.random.randint(1,7,100)
a.mean()

3.61

8. 가격이 10,000원인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0%이고 표준편차가 1%
인 표준 정규 분포를 따른다고 하자. 250일 동안의 주가를 무작위로 생성하시오.

In [31]:
np.random.seed(40)
rate = np.random.normal(0,0.01,250)             # 표준 정규 분포를 따르는 수익율. % 이므로 0과 0.01사이로 조정
price = 10000
for i in range(250):
    price = np.round(price*(1+rate[i]))
    print(int(price), end = ' ')

9939 9926 9858 9950 9766 9720 9943 9992 10063 10169 10174 10200 10260 10351 10246 10232 10187 10237 10217 10087 10117 10128 10131 10260 10370 10413 10574 10541 10396 10539 10542 10508 10419 10374 10235 10256 10110 10054 10062 10011 10116 10214 10222 10178 10234 10261 10262 10328 10310 10382 10259 10225 10228 10115 10059 9855 9994 10057 10280 10226 10282 10273 10406 10388 10563 10452 10519 10501 10384 10382 10194 10215 10269 10165 9977 9994 10073 10066 10150 10130 10121 10209 10123 10206 10278 10339 10286 10300 10146 10208 10348 10172 10119 9994 9706 9704 9540 9481 9564 9728 9731 9648 9674 9506 9518 9503 9580 9495 9489 9476 9460 9585 9435 9380 9421 9350 9264 9038 8894 8811 8762 8743 8679 8711 8801 8828 8879 8771 8703 8672 8970 9002 9022 9051 9032 9004 9151 9167 9177 9185 9213 9178 9096 9177 9256 9327 9383 9407 9224 9165 9127 9148 9081 9228 9088 9129 9050 8954 8888 8871 8842 8913 8932 8929 9011 8962 9129 9291 9249 9125 9212 9353 9329 9199 9207 9183 9224 9306 9185 9170 9014 8994 9043 9117

In [32]:
np.random.seed(40)
rate = np.random.randn(250)                 # 표준 정규 분포 사용
price = 10000
for i in range(250):
    price = np.round(price*(1+rate[i]*0.01))        # 여기서 0.01을 곱해준다
    print(int(price), end = ' ')

9939 9926 9858 9950 9766 9720 9943 9992 10063 10169 10174 10200 10260 10351 10246 10232 10187 10237 10217 10087 10117 10128 10131 10260 10370 10413 10574 10541 10396 10539 10542 10508 10419 10374 10235 10256 10110 10054 10062 10011 10116 10214 10222 10178 10234 10261 10262 10328 10310 10382 10259 10225 10228 10115 10059 9855 9994 10057 10280 10226 10282 10273 10406 10388 10563 10452 10519 10501 10384 10382 10194 10215 10269 10165 9977 9994 10073 10066 10150 10130 10121 10209 10123 10206 10278 10339 10286 10300 10146 10208 10348 10172 10119 9994 9706 9704 9540 9481 9564 9728 9731 9648 9674 9506 9518 9503 9580 9495 9489 9476 9460 9585 9435 9380 9421 9350 9264 9038 8894 8811 8762 8743 8679 8711 8801 8828 8879 8771 8703 8672 8970 9002 9022 9051 9032 9004 9151 9167 9177 9185 9213 9178 9096 9177 9256 9327 9383 9407 9224 9165 9127 9148 9081 9228 9088 9129 9050 8954 8888 8871 8842 8913 8932 8929 9011 8962 9129 9291 9249 9125 9212 9353 9329 9199 9207 9183 9224 9306 9185 9170 9014 8994 9043 9117