In [1]:
import numpy as np

1. 넘파이를 사용하여 다음과 같은 행렬을 만드시오.
<pre>
10 20 30 40
50 60 70 80

In [2]:
np.array([[10,20,30,40],[50,60,70,80]])

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

2.

In [4]:
m = np.array([[ 0, 1, 2, 3, 4], 
                [ 5, 6, 7, 8, 9], 
                [10, 11, 12, 13, 14]])

In [5]:
# 이 행렬에서 값 7 을 인덱싱한다.
m[1,2]

7

In [6]:
# 이 행렬에서 값 14 을 인덱싱한다.
m[-1,-1]

14

In [7]:
# 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
m[1:2, 1:3]

array([[6, 7]])

In [8]:
# 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
m[1:, 2:3]

array([[ 7],
       [12]])

In [10]:
# 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.
m[:-1, 3:]

array([[3, 4],
       [8, 9]])

3. 2번의 행렬 m을 1차원 벡터 f 로 변환한 후 다음의 문제를 푸시오.

In [12]:
f = m.flatten()
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
# 이 배열에서 3의 배수를 찾아라.
f[f%3 == 0]

array([ 0,  3,  6,  9, 12])

In [14]:
# 이 배열에서 4로 나누면 1이 남는 수를 찾아라.
f[f%4 == 1]

array([ 1,  5,  9, 13])

In [22]:
# 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.
f_index = np.logical_and(f%3==0,f%4==1)
f[f_index]

array([9])

4.

In [32]:
np.eye(5,5,k=-1, dtype=int)+np.eye(5,5,k=-1, dtype=int)+np.eye(5,5,k=-1, dtype=int)+np.eye(5,5,k=0, dtype=int)+np.eye(5,5,k=0, dtype=int)+np.eye(5,5,k=1, dtype=int)

array([[2, 1, 0, 0, 0],
       [3, 2, 1, 0, 0],
       [0, 3, 2, 1, 0],
       [0, 0, 3, 2, 1],
       [0, 0, 0, 3, 2]])

5. 0에서 10까지 랜덤 실수값으로 이루어진 5 x 6 형태의 데이터 행렬을 만들고 이 데이터에
대해 다음과 같은 값을 구하시오.

In [36]:
a = np.random.randint(0,11,30).reshape(5,6)
a

array([[ 1,  2,  3,  8,  6,  5],
       [ 5,  1,  3,  7,  1,  7],
       [ 6,  0, 10,  5,  6, 10],
       [ 8, 10,  1,  7, 10,  5],
       [ 4,  8,  2,  1,  9,  3]])

In [37]:
# 전체의 최댓값
a.max()

10

In [38]:
# 각 행의 합
a.sum(axis = 1)

array([25, 24, 37, 41, 27])

In [39]:
# 각 행의 최댓값
a.max(axis = 1)

array([ 8,  7, 10, 10,  9])

In [40]:
# 각 열의 평균
a.mean(axis=0)

array([4.8, 4.2, 3.8, 5.6, 6.4, 6. ])

In [41]:
# 각 열의 최솟값
a.min(axis=0)

array([1, 0, 1, 1, 1, 3])

6. 다음 배열은 첫번째 행(row)에 학번, 두번째 행에 영어 성적, 세번째 행에 수학 성적을 적은
배열이다. 영어 성적을 기준으로 각 열(column)을 재정렬하시오.

In [43]:
a = np.array([[ 1, 2, 3, 4],
        [ 46, 99, 100, 71],
        [ 81, 59, 90, 100]])

In [53]:
eng_index = np.argsort(a[1:2])
a[:, eng_index]

array([[[  1,   4,   2,   3]],

       [[ 46,  71,  99, 100]],

       [[ 81, 100,  59,  90]]])

7. 주사위를 100번 던지는 가상 실험을 파이썬으로 작성하고, 
던져서 나오는 숫자의 평균을 구하시오.

In [56]:
a = np.random.randint(0,7,100)
a.mean()

3.12

8. 가격이 10,000원인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0%이고 표준편차가 1%
인 표준 정규 분포를 따른다고 하자. 250일 동안의 주가를 무작위로 생성하시오.

In [61]:
for i in range(1,251):
    print(10000 + 10000*np.random.randn(1))


[24553.13049588]
[7443.97903232]
[-2158.24541022]
[10864.65393579]
[886.41052113]
[15911.37444373]
[15867.31037471]
[10897.19817459]
[-1607.40209598]
[-10939.36872553]
[1105.66869719]
[4802.25426956]
[18608.19316123]
[7397.09845633]
[15816.26723104]
[16881.53334786]
[4507.09592866]
[619.47990986]
[-5117.69599487]
[5051.31064112]
[8580.91404323]
[6897.06835401]
[11224.42292962]
[24383.42702356]
[4216.34483537]
[504.19880661]
[10925.61113864]
[8297.41840018]
[-2023.80473552]
[11289.06219041]
[125.96742703]
[18491.06340647]
[-110.92721546]
[9111.00569936]
[14381.86883389]
[10740.77805488]
[6262.97542604]
[-7728.0322228]
[28902.19104894]
[-3465.78681482]
[-3572.46707264]
[5769.39390656]
[17328.95210682]
[421.67917036]
[31786.5898787]
[9883.04506628]
[7759.01319206]
[11081.13545391]
[2069.21280495]
[23533.63251953]
[3354.27367115]
[3619.10797581]
[18633.41528104]
[6046.85968483]
[21689.76916937]
[3490.84372915]
[1321.66742336]
[7436.0201895]
[12938.00258508]
[-4670.05754011]
[7683.32828763]